### ASSIGNMENT

1. Create a 4x4 matrix with values ranging from 0 to 3.

In [7]:
import numpy as np
from numpy import random

In [9]:
# 1
random.randint(0,4, size=(4,4))

array([[3, 0, 1, 0],
       [2, 2, 1, 3],
       [3, 3, 0, 3],
       [2, 2, 3, 3]])

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.

In [18]:
# 2

array_1 = random.randint(0,9, size=(4,4))
print(array_1)

[[2 4 1 1]
 [6 3 8 3]
 [0 7 1 3]
 [8 3 7 6]]


In [23]:
array_1_split = np.hsplit(array_1, 2)
array_1_split

[array([[2, 4],
        [6, 3],
        [0, 7],
        [8, 3]]),
 array([[1, 1],
        [8, 3],
        [1, 3],
        [7, 6]])]